### PR TITLE
Update CounterInput.tsx

### PR DESCRIPTION
**Pull request by Tiagopt3**
Added the option to include a min and max parameteres to the counter

### CODE REVIEW

**Comment by layerok** [comment]
I am also waiting for this update

**Comment by kuraydev** [comment]
I will merge this and release a new version tomorrow! @adjustmentlayer 
Really sorry for the extremely long delay. I have some health issues

**Review by kuraydev — APPROVED** [review]

**Comment by kuraydev** [comment]
Hello @adjustmentlayer @Tiagopt3 

The new version [1.0.0](https://github.com/WrathChaos/react-native-counter-input/releases/tag/1.0.0) is released :) Please take a look at it.

Also, @Tiagopt3 
I merged this PR but there were some issues with the PR. I fixed them, please take a look at the code when you have time :)

**Comment by Tiagopt3** [comment]
Thank you! I will have a look! Happy code!

**Pull request merged**
